[package]
name = "nannou-plotter-stuff"
version = "0.1.0"
authors = ["tonyketcham <ketcham.dev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"